version: 2
updates:
  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      opentelemetry:
        patterns:
          - "opentelemetry-*"

  - package-ecosystem: "bundler"
    directory: "/test/docker"
    schedule:
      interval: "weekly"
    groups:
      opentelemetry:
        patterns:
          - "opentelemetry-*"
